import { useEffect, useState } from "react";
import { Footer } from "../components/layout/Footer";
import { API } from "../api/drafts";
import { ensureSession } from "../api/auth";

type Plan = { id: string; name: string; monthly_credits: number | null; price_monthly: number | null; price_yearly: number | null };
type BillingState = { subscription: { plan: string; billing_cycle: string } | null; credits: { balance: number; ledger: Array<{ delta: number; reason: string; created_at: string }> } };
export function BillingPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [state, setState] = useState<BillingState | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState("");
  useEffect(() => { void load(); }, []);
  async function load() {
    try { await ensureSession(); const token = localStorage.getItem("fliki-auth-token") || ""; const headers = { Authorization: "Bearer " + token }; const [plansResponse, stateResponse] = await Promise.all([fetch(API + "/billing/plans"), fetch(API + "/billing/me", { headers })]); if (!stateResponse.ok) throw new Error("请先登录"); setPlans((await plansResponse.json()).plans); setState(await stateResponse.json()); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "加载失败"); }
  }
  async function subscribe(plan: string) { setBusy(plan); setError(null); try { const token = localStorage.getItem("fliki-auth-token") || ""; const response = await fetch(API + "/billing/subscribe", { method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + token }, body: JSON.stringify({ plan, billing_cycle: "monthly" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail?.message || "订阅失败"); setState(body); } catch (subscribeError) { setError(subscribeError instanceof Error ? subscribeError.message : "订阅失败"); } finally { setBusy(""); } }
  return <><main className="billingPage"><nav className="catalogNav"><a href="/index.html">Fliki Studio</a><span><a href="/drafts.html">编辑器</a><a href="/files.html">文件</a><a href="/billing.html">Billing</a></span><a className="catalogButton" href="/drafts.html">开始创作</a></nav><section className="billingHero"><span className="eyebrow">PLANS & CREDITS</span><h1>选择适合你的创作额度</h1><p>套餐和 credits 持久化在当前工作区；真实 Stripe/支付宝支付接入前不会产生扣款。</p>{state && <div className="creditBalance" role="status" aria-live="polite"><strong>{state.credits.balance.toLocaleString()}</strong><span>可用 credits · 当前 {state.subscription?.plan || "free"}</span></div>}</section><section className="planGrid">{plans.map((plan) => <article className={"planCard " + (state?.subscription?.plan === plan.id ? "active" : "")} key={plan.id}><h2>{plan.name}</h2><div className="planPrice">{plan.price_monthly === null ? "定制" : plan.price_monthly === 0 ? "$0" : "$" + plan.price_monthly}<small>/月</small></div><p>{plan.monthly_credits === null ? "按团队需求配置" : plan.monthly_credits.toLocaleString() + " credits / 月"}</p><button disabled={busy !== "" || state?.subscription?.plan === plan.id} aria-busy={busy === plan.id} aria-current={state?.subscription?.plan === plan.id ? "true" : undefined} aria-label={(state?.subscription?.plan === plan.id ? "当前方案 " : (plan.id === "enterprise" ? "联系销售 " : "切换到 ")) + plan.name + " 套餐"} onClick={() => void subscribe(plan.id)}>{busy === plan.id ? "保存中..." : state?.subscription?.plan === plan.id ? "当前方案" : plan.id === "enterprise" ? "联系销售" : "切换方案"}</button></article>)}</section>{error && <p className="billingError">{error}</p>}{state && <section className="ledger"><h2>Credits 流水</h2>{state.credits.ledger.length === 0 ? <p>暂无流水</p> : state.credits.ledger.map((item, index) => <div key={index}><span>{item.reason}</span><b className={item.delta > 0 ? "positive" : "negative"}>{item.delta > 0 ? "+" : ""}{item.delta}</b><small>{item.created_at}</small></div>)}</section>}</main><Footer /></>;
}
