import { useMemo, useState } from "react";
import { Footer } from "../components/layout/Footer";

type Character = { name: string; region: string; style: string; color: string };
const regions = ["US", "UK", "Canada", "Australia", "Germany", "France", "Spain", "Japan", "China", "Brazil", "India", "Singapore"];
const styles = ["商务", "教育", "社交", "新闻", "生活方式", "科技"];
const characters: Character[] = Array.from({ length: 72 }, (_, index) => ({
  name: `${["Alex", "Mia", "Jordan", "Sofia", "Taylor", "Emma"][index % 6]} ${String(index + 1).padStart(2, "0")}`,
  region: regions[index % regions.length],
  style: styles[index % styles.length],
  color: ["#5b6cff", "#48d58b", "#f5a524", "#e85d75", "#8a6cff", "#19b5c5"][index % 6],
}));

export function CharactersPage() {
  const [filter, setFilter] = useState("全部");
  const [search, setSearch] = useState("");
  const shown = useMemo(() => characters.filter((character) => (filter === "全部" || character.region === filter) && character.name.toLowerCase().includes(search.toLowerCase())), [filter, search]);
  return <><main className="catalogPage"><nav className="catalogNav"><a href="/index.html">Fliki Studio</a><span><a href="/features.html">Features</a><a href="/use-cases.html">Use cases</a><a href="/pricing.html">Pricing</a></span><a className="catalogButton" href="/drafts.html">开始创作</a></nav><section className="catalogHero"><span className="eyebrow">AI AVATAR LIBRARY</span><h1>让每个故事都有合适的角色</h1><p>从 72 个真实感数字人中选择，覆盖全球语言、口音和表达风格。直接应用到你的脚本与视频场景。</p><div className="catalogStats"><b>72+<small>角色</small></b><b>80+<small>语言</small></b><b>4K<small>输出画质</small></b></div></section><section className="catalogToolbar"><input aria-label="搜索角色" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索角色..." /><div className="filterRow">{["全部", ...regions].map((item) => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div></section><section className="characterGrid">{shown.map((character) => <article className="characterCard" key={character.name}><div className="characterAvatar" style={{ background: `linear-gradient(145deg, ${character.color}, #151b31)` }}><span>{character.name.split(" ")[0][0]}</span><i>▶</i></div><div className="characterInfo"><strong>{character.name}</strong><span>{character.region} · {character.style}</span><button onClick={() => window.location.href = "/drafts.html?avatar=" + encodeURIComponent(character.name)}>使用角色</button></div></article>)}</section></main><Footer /></>;
}

const featureGroups: Array<[string, string[]]> = [
  ["Create", ["Idea to Video", "Script to Video", "Blog to Video", "PPT to Video", "Record to Video", "Translate Video", "AI Video Generator", "AI Image Generator", "AI Music", "Text to Speech", "Voice Cloning", "AI Avatar"]],
  ["Edit", ["Timeline Editor", "Rich Script Editor", "Auto-edit", "Scene Generator", "Background Remover", "Image Upscaler", "Video Resizer", "Subtitle Generator", "Text Animation", "Transitions", "Stock Media", "Brand Kit"]],
  ["Publish", ["4K Export", "Social Formats", "Team Workspaces", "Review Links", "Video Analytics", "API Access", "Templates", "Custom Fonts", "Watermark Control", "SRT Export", "Audio Mixing", "Version History", "AI Voiceover", "Video Dubbing", "Stock Video Search", "Team Comments", "Scheduled Publishing", "Webhooks"]],
  ["AI Models", ["Flux 2 Klein", "GPT Image 2", "Flux Pro", "Qwen", "Nano Banana 2", "Seedream 4.5", "Veo 3.1", "Sora 2", "Kling 3 Pro", "Runway", "Suno", "Udio"]],
];
export function FeaturesPage() { return <><main className="catalogPage"><nav className="catalogNav"><a href="/index.html">Fliki Studio</a><span><a href="/characters.html">Characters</a><a href="/use-cases.html">Use cases</a><a href="/pricing.html">Pricing</a></span><a className="catalogButton" href="/drafts.html">免费开始</a></nav><section className="catalogHero featureHero"><span className="eyebrow">ONE CREATIVE WORKSPACE</span><h1>从想法到成片，所有工具都在这里</h1><p>用一套工作流完成脚本、画面、声音、数字人和发布。少切换，快出片。</p></section><div className="featureGroups">{featureGroups.map(([title, items]) => <section className="featureGroup" key={title}><h2>{title}</h2><div className="featureList">{(items as string[]).map((item, index) => <a href={"/drafts.html?feature=" + encodeURIComponent(item)} key={item}><span className="featureIcon">{["✦", "◈", "●", "✧"][index % 4]}</span><span><strong>{item}</strong><small>{index % 3 === 0 ? "AI-powered creation" : index % 3 === 1 ? "Fast and flexible" : "Built for teams"}</small></span><em>→</em></a>)}</div></section>)}</div></main><Footer /></>; }

const useCases = [{ id: "marketing", title: "Marketing & Ads", icon: "✦", desc: "批量生产有品牌一致性的广告、产品发布和活动视频。" }, { id: "social", title: "Social Media", icon: "◉", desc: "为 TikTok、Reels、YouTube Shorts 一次生成多个比例版本。" }, { id: "sales", title: "Sales Outreach", icon: "↗", desc: "用个性化视频提升触达、演示和销售转化。" }, { id: "training", title: "Product Training & L&D", icon: "◇", desc: "把复杂流程变成清晰、可复用的学习内容。" }, { id: "education", title: "Educational Courses", icon: "▣", desc: "将课程大纲快速转成有旁白和画面的教学视频。" }, { id: "ecommerce", title: "Ecommerce Product Videos", icon: "□", desc: "让商品卖点在每个渠道都拥有高质量展示。" }, { id: "localization", title: "Localization", icon: "◎", desc: "翻译脚本、配音并同步字幕，面向全球市场发布。" }, { id: "internal", title: "Internal Communications", icon: "☼", desc: "让团队更新、公告和知识分享更有吸引力。" }];
export function UseCasesPage() { return <><main className="catalogPage"><nav className="catalogNav"><a href="/index.html">Fliki Studio</a><span><a href="/features.html">Features</a><a href="/characters.html">Characters</a><a href="/pricing.html">Pricing</a></span><a className="catalogButton" href="/drafts.html">开始创作</a></nav><section className="catalogHero"><span className="eyebrow">BUILT FOR YOUR WORKFLOW</span><h1>每一种业务，都有更快的做法</h1><p>从第一条社交内容到全球化培训库，用 AI 视频工作流把创意变成结果。</p></section><section className="useCaseGrid">{useCases.map((item) => <article id={item.id} className="useCaseCard" key={item.id}><div className="useCaseIcon">{item.icon}</div><h2>{item.title}</h2><p>{item.desc}</p><div className="benchmark"><b>{[3, 5, 8, 10][useCases.indexOf(item) % 4]}×</b><span>更快完成初稿</span></div><a href={"/drafts.html?useCase=" + item.id}>查看工作流 →</a></article>)}</section><section className="apiBanner"><div><span className="eyebrow">API & AUTOMATION</span><h2>把视频生成接入你的产品</h2><p>通过 API 批量创建草稿、管理资产并连接团队工作流。</p></div><a className="catalogButton" href="/docs-api.html">查看 API 文档</a></section></main><Footer /></>; }
