import json
import os
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

SECRET_ENV = {
    ("stock", "pexels"): "PEXELS_API_KEY",
    ("stock", "pixabay"): "PIXABAY_API_KEY",
    ("music", "freesound"): "FREESOUND_API_KEY",
}

_MANAGED_PREFIX = "FLIKI_PROVIDER_"
_ENV_PATH = None


def _env_path():
    global _ENV_PATH
    if _ENV_PATH is None:
        _ENV_PATH = Path(__file__).resolve().parent / ".env"
        # P5E: FLIKI_SECRETS_PATH 覆盖默认 .env 路径, 容器 / 沙箱可指向可写目录.
        override = os.getenv("FLIKI_SECRETS_PATH")
        if override:
            _ENV_PATH = Path(override)
    return _ENV_PATH


def _load_managed_env():
    p = _env_path()
    if not p.exists():
        return {}
    out = {}
    for raw in p.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        if not k.startswith(_MANAGED_PREFIX):
            continue
        out[k] = v.strip().strip(chr(34)).strip(chr(39))
    return out


def _render_managed_env(values):
    lines = []
    p = _env_path()
    if p.exists():
        try:
            existing_text = p.read_text(encoding="utf-8")
        except OSError:
            existing_text = ""
        for raw in existing_text.splitlines():
            stripped = raw.strip()
            if (
                stripped.startswith("# Fliki managed provider keys")
                or stripped.startswith("# 由 provider_config.update_config 写入")
                or stripped.startswith(_MANAGED_PREFIX)
            ):
                continue
            lines.append(raw)
    else:
        lines.append("# Generated by Fliki provider_config.py")
    while lines and not lines[-1].strip():
        lines.pop()
    block = ["", "# Fliki managed provider keys (auto, do not edit by hand)", "# 由 provider_config.update_config 写入，重启后仍生效"]
    for k, v in values.items():
        if v:
            block.append(f"{k}={v}")
    lines.extend(block)
    return chr(10).join(lines) + chr(10)


def _persist_managed_env(values):
    p = _env_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    content = _render_managed_env(values)
    temp_path = p.with_name(f"{p.name}.tmp")
    fd = os.open(str(temp_path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fp:
        fp.write(content)
    os.replace(temp_path, p)
    try:
        os.chmod(p, 0o600)
    except OSError:
        pass


def hydrate_env_from_disk():
    loaded = _load_managed_env()
    for k, v in loaded.items():
        os.environ.setdefault(k, v)
    bare = {k[len(_MANAGED_PREFIX):]: v for k, v in loaded.items() if k.startswith(_MANAGED_PREFIX)}
    for k, v in bare.items():
        os.environ.setdefault(k, v)
    return loaded


def now_epoch():
    return int(datetime.now(timezone.utc).timestamp())


def mask_secret(value):
    if not value:
        return None
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:4]}{chr(42) * 8}{value[-4:]}"


class ProviderUpdateBody(BaseModel):
    enabled: bool | None = None
    is_default: bool | None = None
    priority: int | None = Field(default=None, ge=0, le=1000)
    base_url: str | None = Field(default=None, max_length=1000)
    model: str | None = Field(default=None, max_length=200)
    api_key: str | None = Field(default=None, max_length=4000)
    # P5E: None = 沿用向后兼容默认 (落盘 .env); True = 强制落盘; False = 仅注入当前进程.
    persist: bool | None = None
    extra: dict | None = None


def provider_secret(category, name, config):
    env_name = config.get("api_key_env") or SECRET_ENV.get((category, name))
    return os.getenv(env_name, "") if env_name else ""


def provider_payload(row):
    config = json.loads(row["config_json"] or "{}")
    env_name = config.get("api_key_env") or SECRET_ENV.get((row["category"], row["name"]))
    secret = provider_secret(row["category"], row["name"], config)
    managed_disk = _load_managed_env()
    managed_key = (_MANAGED_PREFIX + env_name) if env_name else None
    persisted = managed_disk.get(managed_key) if managed_key else None
    if persisted:
        source = "managed"
    elif secret:
        source = "env"
    else:
        source = "missing"
    persist_flag = bool(persisted)
    return {
        "id": row["id"], "category": row["category"], "name": row["name"],
        "enabled": bool(row["enabled"]), "is_default": bool(row["is_default"]),
        "priority": row["priority"], "base_url": config.get("base_url"),
        "model": config.get("model"), "extra": config.get("extra", {}),
        "has_api_key": bool(secret), "api_key_masked": mask_secret(secret),
        "is_mock": bool(config.get("is_mock", False)),
        "key_source": source,
        "source": source,
        "persist": persist_flag,
        "api_key_env": env_name,
    }


def seed_runtime_providers(connection):
    providers = [
        ("provider_stock_pexels", "stock", "pexels", 1, 1, 0, {"api_key_env":"PEXELS_API_KEY","base_url":"https://api.pexels.com"}),
        ("provider_stock_minimax", "stock", "minimax_image", 0, 0, 30, {"model":"image-01","api_key_env":"MINIMAX_API_KEY","base_url":"https://api.minimaxi.com"}),
        ("provider_stock_minimax_video", "stock", "minimax_video", 0, 0, 25, {"model":"MiniMax-Hailuo-2.3","api_key_env":"MINIMAX_API_KEY","base_url":"https://api.minimaxi.com"}),
        ("provider_stock_pixabay", "stock", "pixabay", 1, 0, 10, {"api_key_env":"PIXABAY_API_KEY","base_url":"https://pixabay.com/api"}),
        ("provider_tts_edge", "tts", "edge_tts", 1, 1, 0, {"model":"zh-CN-XiaoxiaoNeural"}),
        ("provider_tts_minimax", "tts", "minimax", 0, 0, 40, {"model":"speech-02-turbo","api_key_env":"MINIMAX_API_KEY","base_url":"https://api.minimaxi.com"}),
        ("provider_tts_gpt_sovits", "tts", "gpt_sovits", 0, 0, 50, {"base_url":"http://127.0.0.1:9880","model":"GPT-SoVITS-v2","api_key_env":"FLIKI_GPT_SOVITS_URL"}),
        ("provider_avatar_wav2lip", "avatar", "wav2lip_onnx", 0, 1, 0, {"model_path":"data/models/wav2lip_onnx","ffmpeg_binary":"ffmpeg","auto_download":False,"fps":25.0,"max_dimension":320}),
        ("provider_music_minimax", "music", "minimax_music", 0, 0, 30, {"model":"music-3.0","api_key_env":"MINIMAX_API_KEY","base_url":"https://api.minimaxi.com"}),
        ("provider_music_freesound", "music", "freesound", 1, 1, 0, {"api_key_env":"FREESOUND_API_KEY","base_url":"https://freesound.org/apiv2"}),
        ("provider_music_silence", "music", "silence", 1, 0, 100, {}),
        ("provider_text_mock", "text", "mock", 1, 1, 100, {"is_mock": True}),
        ("provider_stock_mock", "stock", "mock", 1, 0, 100, {"is_mock": True}),
        ("provider_tts_mock", "tts", "mock", 1, 0, 100, {"is_mock": True}),
        ("provider_music_mock", "music", "mock", 1, 0, 100, {"is_mock": True}),
        ("provider_avatar_mock", "avatar", "mock", 1, 0, 100, {"is_mock": True}),
    ]
    for row in providers:
        connection.execute("INSERT OR IGNORE INTO provider_configs (id, category, name, enabled, is_default, priority, config_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", (*row[:-1], json.dumps(row[-1]), now_epoch()))
    connection.commit()


def create_router(get_db):
    router = APIRouter(prefix="/provider-configs", tags=["provider-configs"])

    @router.get("")
    def list_configs(category: str | None = None):
        connection = get_db()
        try:
            seed_runtime_providers(connection)
            if category:
                rows = connection.execute("SELECT * FROM provider_configs WHERE category=? ORDER BY priority,name", (category,)).fetchall()
            else:
                rows = connection.execute("SELECT * FROM provider_configs ORDER BY category,priority,name").fetchall()
            return [provider_payload(row) for row in rows]
        finally:
            connection.close()

    @router.put("/{category}/{name}")
    def update_config(category: str, name: str, body: ProviderUpdateBody):
        connection = get_db()
        try:
            seed_runtime_providers(connection)
            row = connection.execute("SELECT * FROM provider_configs WHERE category=? AND name=?", (category, name)).fetchone()
            if row is None:
                raise HTTPException(status_code=404, detail="Provider config not found")
            config = json.loads(row["config_json"] or "{}")
            if body.api_key is not None:
                env_name = config.get("api_key_env") or SECRET_ENV.get((category, name))
                if not env_name:
                    raise HTTPException(status_code=422, detail="This provider has no local API key slot")
                os.environ[env_name] = body.api_key
                # P5E persist 开关: None/True -> 落盘 .env; False -> 仅注入进程并从 .env 清掉.
                managed = _load_managed_env()
                managed_key = _MANAGED_PREFIX + env_name
                if body.persist is False:
                    managed.pop(managed_key, None)
                    os.environ.pop(managed_key, None)
                else:
                    managed[managed_key] = body.api_key
                    os.environ[managed_key] = body.api_key
                _persist_managed_env(managed)
            for field in ("base_url", "model", "extra"):
                value = getattr(body, field)
                if value is not None:
                    config[field] = value
            enabled = row["enabled"] if body.enabled is None else int(body.enabled)
            is_default = row["is_default"] if body.is_default is None else int(body.is_default)
            priority = row["priority"] if body.priority is None else body.priority
            if is_default:
                connection.execute("UPDATE provider_configs SET is_default=0 WHERE category=?", (category,))
            connection.execute("UPDATE provider_configs SET enabled=?,is_default=?,priority=?,config_json=? WHERE id=?", (enabled, is_default, priority, json.dumps(config), row["id"]))
            connection.commit()
            return provider_payload(connection.execute("SELECT * FROM provider_configs WHERE id=?", (row["id"],)).fetchone())
        finally:
            connection.close()

    @router.delete("/{category}/{name}/secret")
    def delete_secret(category: str, name: str):
        # P5E: 从 .env 清除 managed key, 同步清空当前进程环境.
        connection = get_db()
        try:
            seed_runtime_providers(connection)
            row = connection.execute(
                "SELECT * FROM provider_configs WHERE category=? AND name=?",
                (category, name),
            ).fetchone()
            if row is None:
                raise HTTPException(status_code=404, detail="Provider config not found")
            cfg = json.loads(row["config_json"] or "{}")
            env_name = cfg.get("api_key_env") or SECRET_ENV.get((category, name))
            if not env_name:
                raise HTTPException(status_code=422, detail="This provider has no local API key slot")
            managed = _load_managed_env()
            managed_key = _MANAGED_PREFIX + env_name
            removed = False
            if managed.pop(managed_key, None) is not None:
                _persist_managed_env(managed)
                removed = True
            os.environ.pop(env_name, None)
            os.environ.pop(managed_key, None)
            return {
                "category": category,
                "name": name,
                "env_name": env_name,
                "removed": removed,
            }
        finally:
            connection.close()

    return router
