#!/usr/bin/env python3
# 追加踩坑日志: 2026-07-25 P5D 余项收尾
from pathlib import Path
import datetime
L = Path("D:/workspace/踩坑日志.txt")
ts = "2026-07-25"

entry = chr(10) + "=== " + ts + " P5D 余项收尾 (116/116) ===" + chr(10)
entry += "后端单测: 116/116 绿 (18 个文件). 测试列表:" + chr(10)
entry += "  test_autoedit 7 | test_avatar_clones 10 | test_avatar_image_magic 10 (新) | test_characters 1" + chr(10)
entry += "  test_gpt_sovits_provider 10 | test_p5b_pipeline 6 | test_p5d6 3 | test_p5d7 4 | test_p5d7b 2" + chr(10)
entry += "  test_p5d7c 13 | test_p5d8_async 4 | test_p5d8_preview 5 | test_remotion_runner 6" + chr(10)
entry += "  test_render_progress 5 | test_voice_clones 5 | test_voice_gallery 5 | test_wav2lip_provider 9 | test_workflow_drafts 6" + chr(10)
entry += "前端 build: 593ms OK (avatars.html 7.19kB + env-check.html 8.07kB)" + chr(10)
entry += "Remotion tsc: 改动后未跑, 改的是 AvatarLayout 增字段 + resolveLayout 重写 + avatarBoxStyle 简化, 都需要 UI 触发. 不影响 props.json 形状 (旧字段保留, 新字段可选)" + chr(10)
entry += "compileall: 通过" + chr(10)
entry += "" + chr(10)
entry += "【坑24】P5D-6 _RenderBody 漏 **kwargs 已修复" + chr(10)
entry += "- 修改: tests/test_p5d6_avatar_render.py 第 27 行 __init__ 加 **kwargs" + chr(10)
entry += "- 验证: 3/3 OK (writes_avatar_fields / omits_avatar_src / avatar_node_reached_success)" + chr(10)
entry += "- 影响: P5D-6 测试 mock 现在能接收 workflow_pipeline 传的 resolution kwarg" + chr(10)
entry += "- 启示: 测试 mock 类签名要随生产 render_body_class 调用点同步; P5D-7/7b 已加 **kwargs 是好习惯" + chr(10)
entry += "" + chr(10)
entry += "【坑25】scripts/run_tests.js 写法" + chr(10)
entry += "- 坑: shell_command 14s wall time 限制, python -m unittest discover 会 hang (P5D-8 后台诊断卡死 -> 14s 超时)" + chr(10)
entry += "- 解: Node spawnSync 包装, 写 scripts/run_tests.js (rev3 final, 2026-07-25)" + chr(10)
entry += "  - argv 模式: --modules m1,m2,m3 [--timeout 60000]" + chr(10)
entry += "  - 内部转 unittest tests.<m> 路径, 不依赖 -p regex (unittest 不支持 -p 的 |)" + chr(10)
entry += "  - log 写到 .run/test_run_<ISO>.log, 后查数字看 tail" + chr(10)
entry += "- 批量策略: 5-7 modules / 批, 每批 < 14s. 全量 18 modules 拆 3 批" + chr(10)
entry += "- 坑 2: 不要写 BOM 头 ('\uFEFF' 字面), Node 会解析失败. Node 写文件不加 BOM 也兼容" + chr(10)
entry += "" + chr(10)
entry += "【坑26】shell 14s 限制 + spawnSync 输出截断" + chr(10)
entry += "- 现象: Node spawnSync 实际跑完 (status=0), 但 shell wall time 超时, Select-Object -Last 30 只看到部分 stdout" + chr(10)
entry += "- 解: 看 .run/test_run_*.log 最新文件, 用 grep Ran N tests / ^OK$ / ^FAILED 提取基线" + chr(10)
entry += "- 不要相信 stdout 显示, log 文件才是真相" + chr(10)
entry += "" + chr(10)
entry += "【坑27】假 PNG hang 防御落地" + chr(10)
entry += "- avatar_clone_router.py: size < 256 校验后追加 _validate_image_magic(face_dest, face_ext)" + chr(10)
entry += "- _IMAGE_MAGIC dict 覆盖 6 种扩展: jpg/jpeg (FF D8 FF), png (89 50 4E 47 0D 0A 1A 0A), webp (RIFF), bmp (BM), gif (GIF87a/89a)" + chr(10)
entry += "- 不匹配 -> 422, 错误 detail 含 got / expected bytes" + chr(10)
entry += "- 截断 PNG (只前 4 字节正确) -> 422 (防 ffmpeg 读 0 字节卡死)" + chr(10)
entry += "- 未知扩展 -> pass through (返回 b'', 不抛) - 给后续 Provider 决策" + chr(10)
entry += "- 测试: tests/test_avatar_image_magic.py 10 case 0.040s 全过" + chr(10)
entry += "" + chr(10)
entry += "【坑28】Main.tsx per-shape borderRadius 双处改" + chr(10)
entry += "- AvatarLayout 加 shapeBorderRadii?: { circle?, rounded?, square? }" + chr(10)
entry += "- resolveLayout 重写: 抽出 _shapeRadius(merged, base) helper, 在 base 算好后覆盖 base.borderRadiusPx" + chr(10)
entry += "- avatarBoxStyle 必须改: 1) 移除 shape destructure (resolveLayout 已算好 borderRadiusPx); 2) 删 if/else shape 分支; 3) 直接 style.borderRadius = borderRadiusPx" + chr(10)
entry += "- 不改 avatarBoxStyle 会有 TS6133 (declared but never used) 或 shape undefined 错误" + chr(10)
entry += "- 同步测试: 当前 Python 单测只测 props.json 序列化, 不验 Main.tsx 渲染逻辑; TS 端需手动验证或加 vitest" + chr(10)
entry += "" + chr(10)
entry += "【坑29】mcp__node_repl__js 不能多次复用 const 名" + chr(10)
entry += "- 现象: 在同一 kernel session 多次 declare const fw / code / runner 报 'Identifier has already been declared'" + chr(10)
entry += "- 解: 每次写新脚本要么用 var (可重声明), 要么 mcp__node_repl__js_reset 清 kernel" + chr(10)
entry += "- JS template literal 里嵌套 '\"\"\"' (Python docstring) 会破 JS parser, 用 String.raw 反引号 + chr(10) 拼字符串" + chr(10)
entry += "" + chr(10)
entry += "下一步: 写交付总验收 (HANDOFF 新增 \u00a714 Final Acceptance); 测试 chatgpt/n8n 自动验证场景" + chr(10)
entry += "" + chr(10)

# 用 BOM + UTF-8 append (踩坑日志要兼容 PS Get-Content)
existing = L.read_bytes()
new_bytes = entry.encode("utf-8")
L.write_bytes(existing + new_bytes)
print("[OK] 踩坑日志追加", len(entry), "chars")
print("  total log size:", L.stat().st_size, "bytes")
