#!/usr/bin/env python3
# 追加踩坑日志: Git 首次基线 (2026-07-25)
from pathlib import Path
L = Path("D:/workspace/踩坑日志.txt")
entry = chr(10) + "=== 2026-07-25 Git 首次基线提交 ===" + chr(10)
entry += "commit 4a35904 'P5D 余项收尾基线 + 116/116 测试绿'" + chr(10)
entry += "160 files changed, 19549 insertions(+), master 分支" + chr(10)
entry += "" + chr(10)
entry += "【坑30】Git 首次基线 (HANDOFF §11 '未完成' -> '已完成')" + chr(10)
entry += "- 现象: 项目根目录已 git init 但从未 commit, 用户无 rollback/blame 能力" + chr(10)
entry += "- 解: git config user.name 'Fliki-还原-bot' / user.email 'fliki-bot@local' -> add -A -> commit" + chr(10)
entry += "- .gitignore 改造要点:" + chr(10)
entry += "  + Python: __pycache__/, *.pyc, .pytest_cache/, .venv/" + chr(10)
entry += "  + Node: app/node_modules/, app/dist/, backend/workers/remotion-project/node_modules/, out/, .cache/, bundle/" + chr(10)
entry += "  + Secrets: .env, .env.* (排除 .env.example)" + chr(10)
entry += "  + Runtime data: app/data/, backend/data/, avatar_clone_faces/audios/outputs/" + chr(10)
entry += "  + Backend logs: backend/_uvi.*, _uvicorn.*, server.log, voice-gallery-server.*" + chr(10)
entry += "  + 备份/历史写代码脚本: backend/_backup_*.py, backend/_p5c_write.py" + chr(10)
entry += "  + 测试日志: .run/" + chr(10)
entry += "  + 根级临时: last_*.txt, run_state.txt, check_full.txt, build_handoff_docx.py, check_*.py, check_msg*.py, reset*.py, rewrite_props*.py, count_p5a.py, finalize.py, write_*.py, write_static.py" + chr(10)
entry += "  + Vite/TS: app/vite.log/.err, voice-gallery-vite.log/.err, tsconfig.app.tsbuildinfo" + chr(10)
entry += "  + OS: .DS_Store, Thumbs.db, .vscode/, .idea/" + chr(10)
entry += "- 入仓文件: HANDOFF.md (含 P5D 余项), HANDOFF_P5D7_short.md, PROJECT_STATUS_AND_PLAN.md, README.md, Fliki项目交接文档.docx, voice-gallery.png, backend/, app/, scripts/, research/" + chr(10)
entry += "- 入仓不含: backend/.env (含 API keys), backend/data/* (用户上传/输出/DB), app/dist/, node_modules/, .run/test_run_*.log" + chr(10)
entry += "" + chr(10)
entry += "【坑31】Windows Git LF/CRLF 警告" + chr(10)
entry += "- 现象: git add 后报 'in the working copy of X, LF will be replaced by CRLF'" + chr(10)
entry += "- 解: 无害, 仅行尾风格转换. git config core.autocrlf false 可保留 LF, 但 Windows 默认配置推荐保留 (true)" + chr(10)
entry += "- 不要 git config core.autocrlf input (会让 LF 文件被改); 保持默认即可" + chr(10)
entry += "" + chr(10)
entry += "【坑32】已 git add 但 .gitignore 后改 -> 文件已入仓" + chr(10)
entry += "- 现象: 第一次 add -A 后发现 app/vite.log 没被 ignore (因为 .gitignore 没写对应行)" + chr(10)
entry += "- 解: git rm -r --cached app/vite.log app/vite.err ... (从索引移除但保留工作区文件), 再 commit" + chr(10)
entry += "- 顺序: 1) 写 .gitignore 2) git rm --cached 多余文件 3) git add .gitignore 4) git commit -a" + chr(10)
entry += "" + chr(10)
entry += "下一步: C 段完成, 下一个未完成项 = Docker / 安装清单 (HANDOFF §2 还标 未完成)" + chr(10)
entry += "B 段 (Provider 密钥持久化) 也在 P5E 范围; 但用户已实际跑通 (./backend/.env), 优先级低" + chr(10)
entry += "" + chr(10)
existing = L.read_bytes()
L.write_bytes(existing + entry.encode("utf-8"))
print("[OK] 踩坑日志追加", len(entry), "chars")
print("  total log size:", L.stat().st_size, "bytes")
